# Bộ hỏi đáp Sun FourS Tower – nguồn duy nhất cho trang /hoi-dap và chat trên mọi trang
U = 'https://www.sun-fours-tower.com'
MAP = 'https://maps.app.goo.gl/yy5cwvUcBVJZqtSF9'
def L(href, t): return f'<a href="{href}">{t}</a>'

CATS = [
 ('tong-quan', 'Tổng quan dự án', '🏙️'),
 ('vi-tri', 'Vị trí & kết nối', '📍'),
 ('phap-ly', 'Pháp lý & an toàn', '⚖️'),
 ('bao-lanh', 'Bảo lãnh ngân hàng', '🛡️'),
 ('can-ho', 'Căn hộ & thiết kế', '📐'),
 ('gia', 'Giá & chiết khấu', '💰'),
 ('thanh-toan', 'Thanh toán & vay', '🏦'),
 ('ban-giao', 'Bàn giao, bảo hành & vận hành', '🔑'),
 ('dau-tu', 'Đầu tư & cho thuê', '📈'),
 ('thu-tuc', 'Thủ tục mua & giữ căn', '📝'),
]

KB = [
# ---------- TỔNG QUAN ----------
('tong-quan','su-kien','Có sự kiện giới thiệu Tháp F2 không? Diễn ra khi nào, ở đâu?',
 'Có. Sun Property tổ chức sự kiện <b>Giới thiệu dự án FourS Tower – Tháp F2</b> (“Tọa độ Mùa xuân – Khởi sinh Thịnh vượng”) lúc <b>9:00 Chủ nhật 11/10/2026</b> tại <b>Novotel Danang Premier Han River</b>, 36 Bạch Đằng, Hải Châu, Đà Nẵng. Chương trình 9h00–11h20: đón khách &amp; teabreak, giới thiệu Sun Group và Tháp F2, tư vấn chuyên sâu, <b>bốc thăm may mắn</b> (giải nhất loa Marshall Acton III, giải nhì máy massage Philips PPM3306, giải ba tai nghe Sony WH-CH520). Ngoài ra, <b>Chủ nhật 18/10</b> có sự kiện bán hàng Tòa F2 tại <b>Accost Tây Hồ, Hà Nội</b>. Anh/chị để lại số Zalo, chuyên viên giữ chỗ và gửi thư mời ghi tên.',
 ['su kien','event','hoi thao','novotel','novotel o dau','su kien o dau','to chuc o dau','11/10','chu nhat','gioi thieu du an','ra mat','le mo ban','thu moi','tham du','giu cho su kien','boc tham','qua tang su kien','chuong trinh','agenda','marshall','may man']),
('tong-quan','su-kien-hn','Có sự kiện Tòa F2 ở Hà Nội không?',
 'Có. <b>Sự kiện bán hàng Tòa F2</b> diễn ra <b>Chủ nhật 18/10/2026</b> tại <b>Accost Tây Hồ, Hà Nội</b> – xem mặt bằng, tính dòng tiền đúng căn, hỏi trực tiếp đội dự án. Giờ cụ thể gửi kèm thư mời; anh/chị để lại số Zalo, chuyên viên giữ chỗ và gửi thư mời ghi tên.',
 ['ha noi','tay ho','accost','18/10','su kien ha noi','su kien o ha noi','ngoai bac','mien bac','su kien 18','su kien ngoai bac','su kien mien bac','su kien tai ha noi']),
('tong-quan','chu-dau-tu','Chủ đầu tư Sun FourS Tower là ai? Có phải Sun Group không?',
 'Chủ đầu tư (pháp nhân) là <b>Công ty Cổ phần Địa Cầu</b> (MSDN 0400470419, 36-38 Bạch Đằng, phường Hải Châu, Đà Nẵng), được UBND TP. Đà Nẵng chấp thuận nhà đầu tư tại Quyết định 2755/QĐ-UBND ngày 24/06/2026. Dự án do <b>Sun Property – thương hiệu bất động sản của Tập đoàn Sun Group</b> phát triển.',
 ['chu dau tu','cdt','sun group','sun property','dia cau','cong ty nao','ai lam','ai xay','xay dung boi','tap doan']),
('tong-quan','quy-mo','Dự án có bao nhiêu tòa, bao nhiêu căn?',
 'Sun FourS Tower gồm <b>4 tòa F1, F2, F3, F5</b>, mỗi tòa <b>20 tầng nổi + 2 tầng hầm</b>, cao 77,95 m, tổng <b>2.394 căn hộ</b> trên khoảng 15.406 m² đất, mật độ xây dựng 15,8%. Bốn tòa lấy cảm hứng từ tranh tứ bình: Mai – Trúc – Cúc – Tùng. Tòa đang mở bán là <b>Tòa F2 (Tòa Mai) với 607 căn</b>.',
 ['quy mo','bao nhieu toa','may toa','bao nhieu can','may can','tong so can','4 toa','bon toa','mat do']),
('tong-quan','toa-f2','Tòa F2 (Tòa Mai) có gì đặc biệt?',
 'Tòa F2 là tòa mới mở bán từ 26/09/2026 (chính sách CSBH 4.2): 20 tầng nổi, 2 tầng hầm, <b>8 thang máy chia đều 2 bên</b>, 607 căn. Điểm riêng là <b>vành đai sân vườn tầng 2–7</b> – nhiều căn có sân vườn riêng tới ~69 m² – cùng tầng 2 tiện ích có hồ bơi bốn mùa. ' + L(U+'/toa-f2','Xem trang Tòa F2 →'),
 ['toa f2','toa mai','f2 co gi','dac biet','khac gi','toa nao dang ban','toa dang mo ban']),
('tong-quan','thang-may','Tòa F2 có bao nhiêu thang máy, bao nhiêu tầng hầm?',
 'Tòa F2 có <b>8 thang máy, chia đều 2 bên – mỗi bên 4 thang</b>, giờ cao điểm ít phải chờ. Tòa có <b>2 tầng hầm</b> và 20 tầng nổi; tầng 1 và tầng 20 cao 6 m. Số chỗ đỗ xe chi tiết theo hồ sơ thiết kế, anh/chị cần thì chuyên viên gửi ạ.',
 ['thang may','tang ham','ham xe','bao nhieu tang','may tang','chieu cao','cao bao nhieu','de xe','cho de xe','gui xe']),
('tong-quan','cong-nang-tang','Công năng từng tầng của Tòa F2 thế nào?',
 '<b>Tầng 1</b> (cao 6 m): sảnh đón, căn hộ tầng trệt, khối đế shophouse – cafe. <b>Tầng 2</b>: tầng tiện ích (hồ bơi bốn mùa, gym, yoga, spa, Kids Club, phòng khám Mặt Trời) + 10 căn ban công lớn. <b>Tầng 3–7</b> (gồm 3A thay tầng 4): vành đai sân vườn. <b>Tầng 8–19</b>: tầng điển hình 32 căn/tầng. <b>Tầng 20</b>: tầng trên cùng cao 6 m.',
 ['cong nang','tung tang','tang 1','tang 2','tang 20','tang dien hinh','tang 3a','khong co tang 4','tang 4']),
('tong-quan','tien-do','Dự án đã xây chưa, tiến độ thế nào?',
 'Đang thi công thật: <b>khởi công 21/07/2026</b>, đã nghiệm thu kết cấu móng hầm, <b>hoàn thành dự kiến 30/12/2027</b>. Nhà thầu thi công: Công ty TNHH Xây dựng dân dụng Thái Dương; giám sát & QLDA: Công ty TNHH Tư vấn quản lý dự án Mặt Trời. Thẩm định PCCC: Công văn 518/TĐ-PCCC ngày 23/07/2026.',
 ['tien do','da xay','xay chua','khoi cong','thi cong','hoan thanh','nha thau','dang xay','xay toi dau','pccc','phong chay']),

# ---------- VỊ TRÍ ----------
('vi-tri','dia-chi','Sun FourS Tower ở đâu?',
 'Ngã tư <b>Nguyễn Phước Lan – Minh Mạng</b>, phường Ngũ Hành Sơn (trước là Hòa Quý), TP. Đà Nẵng – trong đại đô thị <b>Sun Riverpolis ~500 ha</b>, ngay bên sông Cổ Cò. <a href="'+MAP+'" target="_blank" rel="noopener">📍 Mở Google Maps chỉ đường ↗</a>',
 ['o dau','dia chi','vi tri','cho nao','duong nao','phuong nao','quan nao','ban do','google map','chi duong','nguyen phuoc lan','minh mang']),
('vi-tri','bien','Cách biển bao xa?',
 'Dự án <b>cách biển Sơn Thủy khoảng 2 km – chừng 5 phút</b>. Sáng ra biển, tối về nhà mà không phải chịu giá căn hộ sát mặt biển; tầng cao còn nhìn được sông, biển và danh thắng Ngũ Hành Sơn.',
 ['bien','cach bien','gan bien','bai bien','son thuy','tam bien','ra bien']),
('vi-tri','san-bay','Từ sân bay về dự án mất bao lâu? Đi Hội An có tiện không?',
 'Khoảng <b>10 phút từ sân bay quốc tế Đà Nẵng</b> – ở xa ra thăm nhà hay đón người thân đều tiện. Dự án kết nối nhanh qua nút giao Hòa Xuân, Đồng Nò 2 và <b>thuận đường đi Hội An, Thánh địa Mỹ Sơn</b>.',
 ['san bay','may bay','hoi an','my son','may phut','di lai','ket noi','trung tam']),
('vi-tri','xung-quanh','Xung quanh dự án có gì, có vắng không?',
 'Không vắng – đây là khu dân cư hiện hữu ở lõi trung tâm Nam Đà Nẵng: <b>5 phút</b> tới AEON Mall, danh thắng Ngũ Hành Sơn, biển Sơn Thủy; <b>6 phút</b> Mega Market; <b>8 phút</b> điểm bắn pháo hoa DIFF, FPT Software – Làng Đại học; <b>10 phút</b> Legend Danang Golf.',
 ['xung quanh','vang','hoang vang','dan cu','aeon','mega market','fpt','lang dai hoc','sieu thi','benh vien','truong hoc','golf']),
('vi-tri','o-xa','Tôi ở xa, làm sao xem thực tế dự án?',
 'Anh/chị để lại số Zalo, chuyên viên <b>gọi video dẫn đi thực tế</b>: dự án, đường ra biển và khu xung quanh. Khi ra Đà Nẵng, bên em đón và dẫn đi xem sa bàn, nhà mẫu miễn phí, không ràng buộc.',
 ['o xa','ngoai tinh','ha noi','sai gon','tp hcm','video','xem thuc te','xem tan noi','khong ra duoc','tham quan','nha mau','sa ban','di xem']),

# ---------- PHÁP LÝ ----------
('phap-ly','du-dieu-kien','Dự án đã đủ điều kiện bán chưa?',
 'Đã đủ. <b>Văn bản 17239/SXD-QLN ngày 19/09/2026</b> của Sở Xây dựng Đà Nẵng xác nhận 2.394 căn hộ hình thành trong tương lai tại 4 lô A3-3, A3-4, A3-5, A3-10 (Tòa F2: 607 căn) <b>đủ điều kiện được bán</b> theo Điều 24 Luật Kinh doanh bất động sản 2023. ' + L(U+'/phap-ly','Xem hồ sơ pháp lý →'),
 ['du dieu kien','dieu kien ban','duoc ban chua','phap ly','17239','so xay dung','giay phep','hop phap','an toan khong']),
('phap-ly','so-do','Có sổ đỏ không? Sở hữu bao lâu?',
 'Mỗi lô đất đều có Giấy chứng nhận quyền sử dụng đất; <b>Tòa F2 trên lô A3-10 – GCN số CP 912579</b>, đất ở đô thị. Theo ghi chú trên giấy chứng nhận, người nhận chuyển quyền được <b>sử dụng đất ổn định lâu dài</b>. Công trình cấp I, tuổi thọ thiết kế 100 năm. Sổ hồng từng căn được làm sau khi bàn giao chính thức.',
 ['so do','so hong','lau dai','so huu','so huu bao lau','bao nhieu nam','50 nam','70 nam','100 nam','thoi han','cap so','co so']),
('phap-ly','hop-dong-mau','Hợp đồng mua bán có được kiểm soát không?',
 'Có. Hợp đồng mua bán căn hộ là <b>hợp đồng theo mẫu đã đăng ký với Sở Công Thương</b> Đà Nẵng (Thông báo 1738/TB-SCT ngày 09/04/2026) – không phải hợp đồng chủ đầu tư tự soạn tùy ý.',
 ['hop dong','hop dong mau','hdmb','so cong thuong','1738','dieu khoan']),
('phap-ly','gioi-han-thu-tien','Chủ đầu tư được thu tiền tối đa bao nhiêu trước khi giao nhà?',
 'Theo Văn bản 17239/SXD-QLN: lần đầu <b>không quá 30%</b> (gồm cọc), <b>không quá 70%</b> khi chưa bàn giao nhà, <b>không quá 95%</b> khi chưa cấp sổ; đặt cọc không quá 5% giá bán. <b>5% cuối</b> nộp vào tài khoản đảm bảo cấp sổ.',
 ['thu tien','toi da','30%','95%','gioi han','thu truoc','5% cuoi','tai khoan dam bao']),
('phap-ly','the-chap','Nghe nói lô đất đang thế chấp ngân hàng, có sao không?',
 'Đúng là các lô đất đang thế chấp tại ngân hàng (NCB, VPBank – theo văn bản của Sở Xây dựng). Sở Xây dựng yêu cầu chủ đầu tư <b>giải chấp phần nhà ở và đất tương ứng trước khi ký hợp đồng mua bán</b> (khoản 2 Điều 183 Luật Nhà ở 2023), nên căn anh/chị ký HĐMB là căn đã giải chấp.',
 ['the chap','giai chap','dang the chap','ncb','vpbank','cam co']),
('phap-ly','bao-tri','Kinh phí bảo trì 2% có bị dùng sai không?',
 'Không được dùng sai: chủ đầu tư phải <b>lập tài khoản riêng</b> nhận và quản lý kinh phí bảo trì 2%, không được dùng vào việc khác (Điều 153 Luật Nhà ở 2023). Giá niêm yết đã gồm khoản này.',
 ['bao tri','phi bao tri','kpbt','2%','quy bao tri']),
('phap-ly','nguoi-nuoc-ngoai','Người nước ngoài, Việt kiều có mua được không?',
 'Theo Văn bản 17239/SXD-QLN, dự án <b>chỉ bán cho tổ chức, cá nhân trong nước</b>, không bán cho tổ chức, cá nhân nước ngoài. Trường hợp Việt kiều, anh/chị nhắn chuyên viên để được kiểm tra điều kiện cụ thể.',
 ['nuoc ngoai','viet kieu','foreigner','nguoi ngoai quoc','quoc tich']),
('phap-ly','phap-ly-ky-tinh','Tôi kỹ tính, nên kiểm tra những giấy tờ gì?',
 'Bên em tổng hợp 8 điểm, mỗi điểm có văn bản: (1) đủ điều kiện bán – 17239/SXD-QLN; (2) sổ đỏ lô đất – CP 912579; (3) bảo lãnh Techcombank 26/09/2026; (4) hợp đồng mẫu – 1738/TB-SCT; (5) giới hạn thu tiền 30/70/95%; (6) giải chấp trước HĐMB; (7) quỹ bảo trì tài khoản riêng; (8) đang thi công thật, PCCC 518/TĐ-PCCC. Anh/chị cần <b>bản scan</b> văn bản nào, chuyên viên gửi qua Zalo để tự đối chiếu.',
 ['ky tinh','giay to','kiem tra gi','ho so','ban scan','van ban goc','check','doi chieu']),

('bao-lanh','bl-la-gi','Bảo lãnh ngân hàng khi mua căn hộ là gì, có tác dụng gì?',
 'Theo <b>Điều 26 Luật Kinh doanh bất động sản 2023</b>, khi bán nhà ở hình thành trong tương lai, chủ đầu tư phải được ngân hàng <b>bảo lãnh nghĩa vụ tài chính</b> đối với người mua. Nói dễ hiểu: nếu chủ đầu tư <b>không bàn giao nhà đúng tiến độ đã cam kết</b> trong hợp đồng và người mua yêu cầu, <b>ngân hàng có trách nhiệm hoàn lại số tiền người mua đã ứng trước</b> theo hợp đồng mua bán và hợp đồng bảo lãnh. Đây là lớp bảo vệ tiền của người mua khi mua căn hộ chưa xây xong.',
 ['bao lanh ngan hang','bao lanh la gi','bao lanh ngan hang la gi','bao lanh de lam gi','tac dung bao lanh','bao lanh co tac dung','bao lanh nghia la','y nghia bao lanh']),
('bao-lanh','bao-lanh','Có ngân hàng bảo lãnh cho người mua không?',
 'Có. Ngày 26/09/2026 <b>Techcombank</b> có văn bản cam kết phát hành thư bảo lãnh nghĩa vụ tài chính của chủ đầu tư cho người mua (Thỏa thuận số MMD20265226177/TTCBLN/FOURS TOWER). Văn bản 17239/SXD-QLN của Sở Xây dựng cũng yêu cầu chủ đầu tư thực hiện bảo lãnh theo Điều 26 Luật Kinh doanh bất động sản 2023.',
 ['bao lanh','techcombank','ngan hang bao lanh','ngan hang nao','ngan hang nao bao lanh','mat tien','rui ro','co bao lanh khong']),
('bao-lanh','bl-pham-vi','Bảo lãnh hoàn lại những khoản nào, trong trường hợp nào?',
 'Bảo lãnh áp dụng khi chủ đầu tư <b>không bàn giao nhà theo tiến độ đã cam kết</b> và người mua có yêu cầu: ngân hàng hoàn lại <b>số tiền ứng trước và các khoản tiền khác</b> theo hợp đồng mua bán, hợp đồng bảo lãnh (Điều 26 Luật KDBĐS 2023). Phạm vi cụ thể ghi trong <b>thư bảo lãnh</b> cấp cho từng căn – anh/chị nên đọc kỹ thư này khi nhận.',
 ['hoan lai','hoan tien','bao lanh nhung gi','bao lanh khoan nao','bao lanh bao nhieu','cham ban giao','khong ban giao','tre han','cham tien do','truong hop nao']),
('bao-lanh','bl-thu','Khi nào người mua nhận được thư bảo lãnh?',
 'Thư bảo lãnh được ngân hàng phát hành <b>cho từng người mua, gắn với hợp đồng mua bán căn hộ</b> của người đó – tức là sau khi ký HĐMB. Ở dự án này, Techcombank đã có <b>văn bản cam kết phát hành thư bảo lãnh ngày 26/09/2026</b>. Khi ký, chuyên viên hỗ trợ anh/chị kiểm tra thư bảo lãnh đúng tên, đúng mã căn.',
 ['thu bao lanh','nhan thu bao lanh','khi nao co thu bao lanh','khi nao nhan bao lanh','phat hanh thu','cap thu bao lanh']),
('bao-lanh','bl-vay','Đã vay ngân hàng rồi thì có cần bảo lãnh nữa không?',
 'Hai việc khác nhau: <b>khoản vay</b> là tiền ngân hàng cho anh/chị mượn để thanh toán; <b>bảo lãnh</b> là cam kết của ngân hàng hoàn lại tiền anh/chị đã đóng nếu chủ đầu tư chậm bàn giao. Có vay vẫn nên giữ bảo lãnh. Người chọn từ chối bảo lãnh được chiết khấu thêm 1% theo CSBH 4.2.',
 ['can bao lanh','co can bao lanh','da vay','vay roi','vay va bao lanh','vay thi can bao lanh','khac gi vay','vay co can bao lanh']),
('bao-lanh','bl-kiem-tra','Làm sao kiểm tra bảo lãnh là thật?',
 'Đối chiếu 3 thứ: (1) <b>văn bản cam kết của Techcombank</b> ngày 26/09/2026, thỏa thuận số MMD20265226177/TTCBLN/FOURS TOWER; (2) <b>VB 17239/SXD-QLN</b> của Sở Xây dựng yêu cầu thực hiện bảo lãnh; (3) <b>thư bảo lãnh cấp cho chính căn của anh/chị</b> – ghi đúng tên, mã căn, số hợp đồng; anh/chị có thể liên hệ Techcombank để xác thực. Cần bản scan văn bản cam kết, chuyên viên gửi qua Zalo.',
 ['kiem tra bao lanh','bao lanh co that','bao lanh that','bao lanh gia','xac thuc','xac minh','co that khong','tin duoc khong']),

# ---------- CĂN HỘ ----------
('can-ho','loai-can','Tòa F2 có những loại căn nào, diện tích bao nhiêu?',
 'Diện tích thông thủy tham khảo: <b>Studio ~30–34 m²</b>, <b>1PN ~42 m²</b>, <b>1PN+ ~47–61 m²</b> (có phòng đa năng làm phòng ngủ nhỏ), <b>2PN ~59–64 m²</b>, <b>3PN góc ~85–87 m²</b>. Tầng 8–19 mỗi tầng 32 căn.',
 ['loai can','dien tich','studio','1pn','2pn','3pn','1pn+','phong ngu','m2','rong bao nhieu','bao nhieu met']),
('can-ho','san-vuon','Căn hộ sân vườn (FourS Jardin) là gì?',
 'Là dòng căn có <b>sân vườn riêng</b> – “villa giữa tầng không”, chỉ có ở <b>tầng 2–7</b> Tòa F2. Ví dụ tầng 3: căn F2-03-30, F2-03-31 thông thủy ~54,6 m² kèm <b>sân vườn ~69 m²</b>; căn góc 3PN F2-03-24 ~87 m² kèm sân vườn ~47,6 m². Tầng 2 có 10 căn ban công lớn ~8–23 m² cạnh hồ bơi. Số lượng ít, thường hết sớm.',
 ['san vuon','jardin','foursjardin','ban cong lon','villa','vuon rieng','tang 3']),
('can-ho','view','Căn nào view đẹp? Có view biển, pháo hoa không?',
 'Tầng cao Tòa F2 có căn nhìn <b>sông Cổ Cò, biển, danh thắng Ngũ Hành Sơn</b> và hướng <b>điểm bắn pháo hoa DIFF</b>. Mỗi căn một hướng view khác nhau – anh/chị nhắn tầm tài chính, chuyên viên lọc căn view đẹp còn trống.',
 ['view','nhin ra','phao hoa','diff','view bien','view song','tang cao','huong nao','dong nam']),
('can-ho','mat-bang','Xem mặt bằng tầng và mặt bằng căn ở đâu?',
 'Trang Tòa F2 có mặt bằng từng tầng (tầng 1, 2, 3, 3A, 5, 6, 7, 8–19) và mặt bằng 7 loại căn, bấm để phóng to xem mã căn, diện tích tim tường và thông thủy. ' + L(U+'/toa-f2','Xem mặt bằng →'),
 ['mat bang','layout','ban ve','so do can','thiet ke can']),
('can-ho','ban-giao-hoan-thien','Căn hộ bàn giao thô hay có nội thất?',
 'Bàn giao <b>hoàn thiện cơ bản</b>: tường, trần thạch cao sơn bả hoàn thiện (sơn Dulux/Jotun hoặc tương đương); sàn khách, bếp lát gạch, phòng ngủ lát gạch hoặc gỗ công nghiệp; cửa nhôm Xingfa kính an toàn; cửa chính gỗ công nghiệp chống cháy, phụ kiện Hafele hoặc tương đương; điện chiếu sáng hoàn thiện. Khách tự trang bị nội thất, thiết bị bếp, vệ sinh, bình nóng lạnh, điều hòa (có sẵn ống chờ).',
 ['noi that','ban giao tho','hoan thien','tieu chuan ban giao','ban giao gi','dieu hoa','bep','thiet bi','san go','cua']),
('can-ho','gia-dinh','Gia đình 3–5 người nên chọn căn nào?',
 'Vợ chồng trẻ, 1 con nhỏ: <b>1PN+ (~47–61 m²)</b> – có phòng đa năng làm phòng ngủ nhỏ. Gia đình 3–4 người: <b>2PN (~59–64 m²)</b>. Gia đình nhiều thế hệ: <b>3PN góc (~85–87 m²)</b>. Muốn có khoảng xanh riêng cho trẻ nhỏ, ông bà: <b>căn sân vườn tầng 2–7</b>, sân vườn tới ~69 m², ngay tầng tiện ích có hồ bơi, Kids Club.',
 ['giadinh','nen chon can','chon can nao','can nao hop','tu van can','3 nguoi','4 nguoi','5 nguoi','con nho','mua de o','de o','o cho','nguoi gia','ong ba','vo chong','nhieu the he']),
('can-ho','tien-ich','Có những tiện ích gì?',
 'Tầng 2: <b>hồ bơi bốn mùa</b>, gym, yoga, spa, sauna, Kids Club, sinh hoạt cộng đồng, <b>phòng khám Mặt Trời</b>; khối đế shophouse, cafe, co-working. Ngoại khu: <b>công viên ven sông Hyde Park ~50 ha</b> với 6 phân khu (bến du thuyền, nghệ thuật, thể thao, trẻ em, phong cách sống, ven hồ).',
 ['tien ich','ho boi','be boi','gym','spa','sauna','kids','tre em','cong vien','hyde park','phong kham','cafe']),

# ---------- GIÁ ----------
('gia','gia-ban','Giá căn hộ Tòa F2 bao nhiêu?',
 'Theo giỏ hàng cập nhật 03/10/2026 (đã gồm VAT & phí bảo trì, <b>trước chiết khấu</b>): <b>Studio từ ~1,9 tỷ</b>, 1PN từ ~2,22 tỷ, 1PN+ từ ~2,65 tỷ, 2PN từ ~4,13 tỷ, 3PN từ ~5,91 tỷ; đơn giá khoảng 53–78 triệu/m² thông thủy tùy tầng, hướng. ' + L(U+'/gio-hang','Xem giỏ hàng →'),
 ['gia can','gia ban','bao nhieu tien','nhieu tien','gia ban','bang gia','gia bao nhieu','trieu m2','don gia','re nhat','dat khong','gia tot']),
('gia','chiet-khau','Chiết khấu tối đa bao nhiêu, gồm những gì?',
 'Cộng dồn tới <b>19%</b>, tính trên giá chưa VAT & phí bảo trì: <b>Early Bird 3%</b> (có thời hạn) + <b>không vay 3%</b> + <b>từ chối bảo lãnh ngân hàng 1%</b> (tùy chọn) + <b>thanh toán sớm</b> 2,5% (50%) / 5% (70%) / 12% (95%) nếu thanh toán <b>trước 25/10/2026</b>. Ưu đãi thanh toán sớm không áp dụng cùng gói hỗ trợ lãi suất.',
 ['chiet khau','ck','giam gia','khuyen mai','uu dai','19%','early bird','thanh toan som','12%']),
('gia','gia-sau-ck','Giá sau chiết khấu tính thế nào?',
 'Giá chưa VAT & phí bảo trì = giá niêm yết ÷ 1,12. Trừ lần lượt các khoản chiết khấu, rồi cộng VAT 10% và kinh phí bảo trì 2% (tính trên giá sau chiết khấu) ra tổng tiền phải trả. Bảng tính tự làm việc này cho từng căn. ' + L(U+'/bang-tinh-f2','Mở bảng tính dòng tiền →'),
 ['sau chiet khau','cach tinh','tinh gia','gia thuc','phai tra bao nhieu','gia cuoi','tong tien']),
('gia','gia-da-gom','Giá niêm yết đã gồm VAT và phí bảo trì chưa?',
 'Đã gồm <b>VAT 10%</b> và <b>kinh phí bảo trì 2%</b>, nhưng <b>chưa trừ chiết khấu</b>. Phí quản lý được miễn 2 năm đầu kể từ khi nhận bàn giao chính thức.',
 ['vat','thue','da gom','bao gom','gom chua','phi phat sinh','chi phi khac']),
('gia','qua-tang','Mua Tòa F2 được tặng gì?',
 '🎁 <b>Miễn phí dịch vụ quản lý 2 năm</b> kể từ ngày nhận bàn giao chính thức · 📈 <b>Lãi 8%/năm</b> khi thanh toán trước hạn (ít nhất 10 ngày) bằng vốn tự có · ⭐ <b>Tích thưởng Sun Signature</b> 0,7% (Silver) – 1% (Gold) – 1,5% (Platinum) – 2% (Infinity) giá trị HĐMB, chi tiêu trong hệ sinh thái Sun Group.',
 ['qua tang','duoc tang','tang gi','duoc gi','mien phi','sun signature','tich thuong','8%','lai 8']),
('gia','han-uu-dai','Ưu đãi đến khi nào?',
 'Chiết khấu thanh toán sớm (2,5% / 5% / 12%) áp dụng khi thanh toán <b>trước 25/10/2026</b>. Early Bird 3% cũng có thời hạn. Các ưu đãi miễn phí quản lý 2 năm, hỗ trợ lãi suất 24 tháng theo chính sách CSBH 4.2 áp dụng từ 26/09/2026.',
 ['den khi nao','het han','25/10','con bao lau','bao gio het','thoi han uu dai']),

# ---------- THANH TOÁN & VAY ----------
('thanh-toan','tien-do-tt','Tiến độ thanh toán thế nào?',
 'Cọc <b>100 triệu</b> (3PN: 150 triệu) khi ký Hợp đồng thực hiện nguyện vọng → <b>ngày thứ 15</b> bổ sung đủ 15%, sau đó ký HĐMB → mỗi khoảng 3 tháng 10% (ngày 105, 195, 285…) → đủ <b>70% là nhận nhà</b> (dự kiến 31/05/2028). Không vay: 25% tiếp theo chia 5 đợt 5%, <b>5% cuối</b> nộp vào tài khoản đảm bảo cấp sổ. ' + L(U+'/bang-tinh-f2','Xem lịch theo ngày →'),
 ['tien do thanh toan','thanh toan','dong tien','may dot','lich thanh toan','dot','gop','tra gop','chia dot']),
('thanh-toan','vay','Vay ngân hàng được bao nhiêu, lãi suất thế nào?',
 'Ngân hàng do chủ đầu tư chỉ định cho vay <b>tối đa 70%</b>. Chủ đầu tư <b>hỗ trợ lãi suất 0% tối đa 24 tháng</b> từ lần giải ngân đầu (không muộn hơn 31/01/2029), <b>ân hạn nợ gốc</b> trong thời gian hỗ trợ và <b>miễn phí trả nợ trước hạn</b>.',
 ['vay','ngan hang','lai suat','0%','ho tro lai','an han','giai ngan','khoan vay','tra no']),
('thanh-toan','von-25','Vốn ít thì cần bao nhiêu tiền để nhận nhà?',
 'Vay 70% thì chỉ cần khoảng <b>25% vốn tự có</b> đến khi nhận nhà, chia 3 lần trong ~3,5 tháng đầu: cọc 100 triệu → đủ 15% ngày thứ 15 → thêm 10% ngày thứ 105. Ví dụ căn ~2,9 tỷ (1PN+, 2 phòng ngủ nhỏ) cần khoảng <b>725 triệu</b>.',
 ['von it','it von','can bao nhieu von','von tu co','25%','co bao nhieu','chuan bi bao nhieu','725','du von']),
('thanh-toan','tra-hang-thang','Sau 24 tháng hỗ trợ thì trả hàng tháng bao nhiêu?',
 'Khoản trả hàng tháng phụ thuộc giá căn, số tiền vay, thời hạn vay và lãi suất ngân hàng tại thời điểm hết hỗ trợ. Anh/chị cho em biết căn quan tâm, chuyên viên gửi <b>lịch vay chi tiết + phương án cho thuê bù khoản vay</b> qua Zalo.',
 ['hang thang','moi thang','tra bao nhieu','sau 24 thang','het ho tro','lai tha noi','tra ngan hang']),
('thanh-toan','khong-vay','Không vay ngân hàng thì có lợi gì?',
 'Không dùng gói hỗ trợ lãi suất được <b>trừ thêm 3%</b> và <b>giãn tiến độ tới khoảng 45 tháng</b>; nếu thanh toán sớm trước 25/10/2026 còn được thêm 2,5–12%. Thanh toán trước hạn bằng vốn tự có được hưởng lãi 8%/năm.',
 ['khong vay','tra thang','tien mat','co san von','khong can vay','gian tien do','45 thang']),
('thanh-toan','tt-som','Thanh toán sớm 95% thì được gì?',
 'Thanh toán <b>95% trước 25/10/2026</b> được chiết khấu thanh toán sớm <b>12%</b> (cộng với Early Bird 3%, không vay 3%, có thể thêm 1% từ chối bảo lãnh). Ví dụ trên trang: căn 2 phòng ngủ ~2,9 tỷ, thanh toán nhanh chỉ còn khoảng 2,7 tỷ.',
 ['95%','thanh toan som','tra het','tra 1 lan','mot lan','thanh toan nhanh']),
('bao-lanh','tu-choi-bao-lanh','“Từ chối bảo lãnh 1%” nghĩa là gì, có nên chọn?',
 'Là tùy chọn: người mua không lấy thư bảo lãnh ngân hàng thì được trừ thêm 1%. Đổi lại sẽ không có lớp bảo vệ ngân hàng hoàn tiền nếu chủ đầu tư không bàn giao. Người mua thận trọng nên <b>giữ bảo lãnh</b>; ai đã yên tâm với Sun Group có thể chọn lấy 1%.',
 ['tu choi bao lanh','1%','nen lay bao lanh','lay bao lanh','bo bao lanh','khong lay bao lanh']),

# ---------- BÀN GIAO ----------
('ban-giao','khi-nao','Khi nào nhận nhà?',
 'Tòa F2: thanh toán đủ 70% là <b>nhận nhà sử dụng dự kiến 31/05/2028</b> (chính sách Sun Early Key), sau khi dự án nghiệm thu đưa vào sử dụng. Tòa F1, F5 dự kiến 31/03/2028.',
 ['nhan nha','khi nao','bao gio','ban giao','bao lau nua','nam nao','2028','vao o']),
('ban-giao','bh-thoi-han','Căn hộ được bảo hành bao lâu?',
 'Theo <b>Luật Nhà ở</b>, nhà chung cư được bảo hành <b>tối thiểu 60 tháng (5 năm)</b> kể từ khi hoàn thành xây dựng, nghiệm thu đưa vào sử dụng. Trang thiết bị gắn với căn hộ (thiết bị điện, cửa, khóa…) bảo hành theo <b>thời hạn của nhà sản xuất</b>. Thời hạn và cách thức bảo hành cụ thể ghi trong <b>hợp đồng mua bán theo mẫu</b> đã đăng ký với Sở Công Thương (1738/TB-SCT).',
 ['bao hanh','bao hanh bao lau','thoi han bao hanh','bao hanh may nam','bao hanh 5 nam','bao hanh bao nhieu nam','bao hanh thiet bi']),
('ban-giao','bh-pham-vi','Bảo hành những hạng mục nào, trường hợp nào không được bảo hành?',
 'Bảo hành gồm sửa chữa, khắc phục hư hỏng <b>kết cấu</b> (khung, cột, dầm, sàn, tường, trần, mái), các phần <b>ốp, lát, trát</b>, <b>hệ thống điện, cấp nước, thoát nước</b>, và các trường hợp <b>nghiêng, lún, nứt, thấm</b> theo quy định và hợp đồng. Thường <b>không</b> thuộc bảo hành: hư hỏng do người dùng gây ra hoặc tự ý cải tạo, nội thất và thiết bị khách tự lắp thêm. Phạm vi chính xác theo điều khoản bảo hành trong HĐMB.',
 ['bao hanh nhung gi','hang muc bao hanh','bao hanh gom','pham vi bao hanh','khong duoc bao hanh','tham','tham dot','nut','lun','nghieng','hu hong','dot nuoc']),
('ban-giao','bh-cach','Căn hộ có hư hỏng thì báo bảo hành thế nào?',
 'Báo cho <b>Ban quản lý tòa nhà</b> hoặc bộ phận chăm sóc khách hàng của chủ đầu tư theo kênh ghi trong hợp đồng và biên bản bàn giao; ghi lại hình ảnh, thời điểm phát sinh để được xử lý nhanh. Anh/chị cần hỗ trợ kết nối, chuyên viên tư vấn hỗ trợ ngay cả sau khi bàn giao.',
 ['bao hanh the nao','bao hanh o dau','bao bao hanh','yeu cau bao hanh','sua chua','ai sua','lien he bao hanh','hu thi sao','hu thi','bao ai','hong thi']),
('ban-giao','phi-quan-ly','Phí quản lý bao nhiêu?',
 'Mua Tòa F2 được <b>miễn phí dịch vụ quản lý 2 năm</b> kể từ ngày nhận bàn giao chính thức. Mức phí sau đó theo quy định của ban quản lý tòa nhà tại thời điểm vận hành.',
 ['phi quan ly','phi dich vu','phi hang thang','quan ly toa nha','van hanh','ban quan ly']),
('ban-giao','cap-so','Khi nào có sổ hồng?',
 'Sổ hồng từng căn được làm sau khi bàn giao chính thức; 5% cuối giá trị căn nộp vào <b>tài khoản đảm bảo cấp sổ</b> và chỉ thanh toán khi có sổ – chủ đầu tư không được thu quá 95% khi chưa cấp sổ.',
 ['so hong','khi nao co so','lam so','cap so','giay chung nhan can ho']),

# ---------- ĐẦU TƯ ----------
('dau-tu','nen-dau-tu','Mua để đầu tư cho thuê có ổn không?',
 'Khách đầu tư hay chọn <b>Studio, 1PN</b> vì tổng tiền thấp, dễ cho thuê; vị trí gần biển, sân bay, AEON Mall, FPT – Làng Đại học thuận lợi cho thuê. Vay 70% thì vốn bỏ ra chỉ khoảng 25% đến khi nhận nhà. Chuyên viên gửi phương án dòng tiền cụ thể từng căn.',
 ['dau tu','cho thue','sinh loi','loi nhuan','an loi','co lai','thanh khoan','ban lai','luot song','gia tang']),
('dau-tu','can-dau-tu','Đầu tư nên chọn căn nào?',
 'Ngân sách dưới 2,5 tỷ: <b>Studio, 1PN</b> – dễ cho thuê. 2,5–3,5 tỷ: <b>1PN+</b> có phòng đa năng, hợp gia đình trẻ thuê dài hạn. Muốn hàng hiếm: <b>căn sân vườn tầng 2–7</b> hoặc <b>3PN góc</b> view sông, biển – số lượng ít.',
 ['dau tu','chon can nao','dau tu nen chon','dau tu can nao','can dau tu','dau tu loai nao','cho thue can nao','dau tu chon']),
('dau-tu','so-sanh','So với dự án khác ở Đà Nẵng thì sao?',
 'Điểm khác của Tòa F2: thương hiệu <b>Sun Group</b>, <b>pháp lý đủ điều kiện bán + bảo lãnh Techcombank</b>, căn <b>sân vườn riêng</b> hiếm có, cách biển ~2 km nhưng giá chưa tới mức căn sát biển, và chính sách <b>vay 70% – 0% lãi 24 tháng</b>. Muốn so sánh cụ thể với dự án anh/chị đang cân nhắc, nhắn tên dự án để chuyên viên lập bảng so sánh.',
 ['so sanh','du an khac','hon gi','vi sao chon','tai sao','khac biet','canh tranh']),

# ---------- THỦ TỤC ----------
('thu-tuc','giu-can','Làm sao để giữ căn?',
 'Gọi hoặc nhắn Zalo <b>0904 567 009</b> để kiểm tra căn còn trống, rồi đặt cọc giữ chỗ <b>100 triệu</b> (3PN: 150 triệu) và ký Hợp đồng thực hiện nguyện vọng. Căn đẹp, căn sân vườn thường hết trước – nên kiểm tra sớm.',
 ['giu can','giu cho','dat cho','dat coc','coc','coc bao nhieu','mua the nao','muon mua']),
('thu-tuc','giay-to','Mua cần giấy tờ gì?',
 'Cá nhân cần <b>CCCD</b> (vợ chồng mua chung thì kèm giấy tờ của cả hai). Khi vay ngân hàng, ngân hàng sẽ hướng dẫn thêm hồ sơ chứng minh thu nhập. Chuyên viên gửi danh sách đầy đủ trước khi ký.',
 ['giay to','can gi','cccd','can cuoc','ho so mua','thu tuc','ho so vay']),
('thu-tuc','hoan-coc','Đặt cọc rồi đổi ý có lấy lại tiền được không?',
 'Điều kiện hoàn/chuyển cọc ghi trong Hợp đồng thực hiện nguyện vọng của từng giai đoạn. Anh/chị nhắn chuyên viên gửi <b>mẫu hợp đồng</b> để đọc kỹ trước khi cọc.',
 ['doi y','dat coc roi','coc roi','khong mua nua','hoan coc','lay lai tien','huy coc','mat coc','tra lai coc']),
('thu-tuc','moi-gioi','Ai đang tư vấn cho tôi? Mua qua đây có giá khác không?',
 'Tư vấn bởi <b>Hoàng Phạm Đình Hiệp</b> – Hotline/Zalo 0904 567 009. Đơn vị tư vấn, môi giới chỉ định của dự án là Công ty TNHH Bất động sản S-Realty Đà Nẵng (Thông báo 57B/2026/TB-DCC). Giá và chính sách theo bảng giá chính thức của chủ đầu tư.',
 ['ai tu van','moi gioi','dai ly','s-realty','srealty','gia khac','lien he','so dien thoai','hotline']),
('thu-tuc','gio-hang-con','Còn bao nhiêu căn, còn căn đẹp không?',
 'Ngày 03/10/2026 giỏ hàng tổng hợp có <b>204 căn đang bán</b> (178 căn Tòa F2, 22 căn F5, 4 căn F1). Giỏ hàng thay đổi hằng ngày do có căn đã giao dịch – nhắn tầm tài chính, chuyên viên gửi danh sách căn còn trống mới nhất. ' + L(U+'/gio-hang','Xem giỏ hàng →'),
 ['con bao nhieu','con can','con khong','het chua','gio hang','can trong','can dep','con can dep']),
]
