// Nội dung toàn site. Sửa ở đây rồi chạy `npm run build`.
// Số liệu ghi "dự kiến"/"tham khảo" khi chủ đầu tư chưa công bố chính thức.

export const site = {
  domain: "https://fpt-city.com",
  name: "FPT City Đà Nẵng",
  // Link Google Drive mặc định; mỗi trang có thể ghi đè bằng `drive`.
  drive: "https://drive.google.com/drive/folders/THAY_ID_THU_MUC",
  updated: "2026-10-10",
};

export const investor = "Công ty Cổ phần Đô thị FPT Đà Nẵng (FPT City) – thành viên Tập đoàn FPT";

/* ---------------- FPT PLAZA ---------------- */
export const plazas = [
  {
    slug: "fpt-plaza-1",
    stats: [["586", "Căn hộ"], ["15", "Tầng nổi"], ["1–3PN", "Loại căn"], ["Ở ngay", "Đã bàn giao"]],
    name: "FPT Plaza 1",
    status: "resale",
    statusLabel: "Đã bàn giao · Chuyển nhượng",
    title: "FPT Plaza 1 Đà Nẵng – Giá chuyển nhượng căn hộ FPT Plaza 1 mới nhất",
    description: "Căn hộ FPT Plaza 1 – tòa chung cư đầu tiên tại FPT City Đà Nẵng, đã bàn giao và có sổ. Nhận giỏ hàng chuyển nhượng, giá FPT Plaza 1 và mặt bằng căn hộ qua Google Drive.",
    keywords: "FPT Plaza 1, căn hộ FPT Plaza 1, giá FPT Plaza 1, chung cư FPT Plaza 1 Đà Nẵng, mua bán FPT Plaza 1",
    lead: "Tòa căn hộ đầu tiên của khu đô thị FPT City – cộng đồng cư dân hiện hữu, tiện ích đã vận hành, phù hợp mua ở ngay hoặc cho thuê.",
    specs: [
      ["Quy mô", "1 tầng hầm, 15 tầng nổi"],
      ["Số căn hộ", "586 căn"],
      ["Loại căn", "1PN, 2PN, 3PN"],
      ["Tình trạng", "Đã bàn giao, cư dân đang sinh sống"],
      ["Hình thức", "Chuyển nhượng thứ cấp"],
    ],
    highlights: ["Ở ngay – không chờ xây dựng", "Dòng tiền cho thuê ổn định từ kỹ sư, giảng viên FPT", "Pháp lý rõ ràng, xem nhà thực tế", "Giá chuyển nhượng đa dạng theo tầng, hướng"],
    units: [["1PN", "~46 m²"], ["2PN", "~68 m²"], ["3PN", "~82 m²"]],
    cta: "Nhận giỏ hàng chuyển nhượng FPT Plaza 1",
    faq: [
      ["FPT Plaza 1 bàn giao khi nào?", "FPT Plaza 1 đã hoàn thành và bàn giao, hiện có cư dân sinh sống. Giao dịch hiện tại chủ yếu là chuyển nhượng."],
      ["Mua FPT Plaza 1 có xem nhà trực tiếp được không?", "Có. Đăng ký để chuyên viên gửi giỏ hàng và đặt lịch xem căn thực tế."],
    ],
  },
  {
    slug: "fpt-plaza-2",
    stats: [["~700", "Căn hộ"], ["25", "Tầng nổi"], ["2–3PN", "Loại căn"], ["2023", "Năm bàn giao"]],
    name: "FPT Plaza 2",
    status: "resale",
    statusLabel: "Đã bàn giao · Chuyển nhượng",
    title: "FPT Plaza 2 Đà Nẵng – Giá bán căn hộ FPT Plaza 2 chuyển nhượng",
    description: "Căn hộ FPT Plaza 2 tại FPT City Đà Nẵng: 25 tầng, khoảng 700 căn 2–3 phòng ngủ, đã bàn giao 2023. Nhận giá chuyển nhượng FPT Plaza 2 và mặt bằng qua Google Drive.",
    keywords: "FPT Plaza 2, căn hộ FPT Plaza 2, giá FPT Plaza 2, chung cư FPT Plaza 2 Đà Nẵng, bán căn hộ FPT Plaza 2",
    lead: "Tòa căn hộ 25 tầng đã bàn giao năm 2023, thiết kế 2–3 phòng ngủ cho gia đình, view sông – biển thoáng đãng.",
    specs: [
      ["Quy mô", "25 tầng nổi, tầng hầm"],
      ["Số căn hộ", "~700 căn"],
      ["Loại căn", "2PN, 3PN"],
      ["Tình trạng", "Đã bàn giao năm 2023"],
      ["Hình thức", "Chuyển nhượng thứ cấp"],
    ],
    highlights: ["Căn hộ gia đình 2–3PN", "Tầng cao view sông Cổ Cò, biển", "Nhận nhà ở ngay", "Hỗ trợ vay ngân hàng khi chuyển nhượng"],
    units: [["2PN", "~56 – 70 m²"], ["3PN", "~75 – 90 m²"]],
    cta: "Nhận giỏ hàng chuyển nhượng FPT Plaza 2",
    faq: [
      ["FPT Plaza 2 có bao nhiêu căn?", "FPT Plaza 2 có khoảng 700 căn hộ 2–3 phòng ngủ trên 25 tầng nổi."],
      ["Giá FPT Plaza 2 hiện nay thế nào?", "Giá chuyển nhượng thay đổi theo tầng, hướng và nội thất. Đăng ký để nhận giỏ hàng cập nhật."],
    ],
  },
  {
    slug: "fpt-plaza-3",
    stats: [["837", "Căn hộ"], ["25", "Tầng nổi"], ["2", "Tầng hầm"], ["2026", "Dự kiến hoàn thành"]],
    name: "FPT Plaza 3",
    status: "primary",
    statusLabel: "Hoàn thiện · Nhận nhà",
    title: "FPT Plaza 3 Đà Nẵng – Bảng giá & tiến độ căn hộ FPT Plaza 3",
    description: "Căn hộ FPT Plaza 3 tại FPT City Đà Nẵng: 25 tầng, 2 hầm, 837 căn hộ. Cập nhật tiến độ, bảng giá FPT Plaza 3, mặt bằng và chính sách qua link Google Drive.",
    keywords: "FPT Plaza 3, căn hộ FPT Plaza 3, giá FPT Plaza 3, tiến độ FPT Plaza 3, chung cư FPT Plaza 3 Đà Nẵng",
    lead: "Tòa căn hộ 25 tầng với 837 căn, tiếp nối thành công của FPT Plaza 1 và 2, thi công từ đầu năm 2024.",
    specs: [
      ["Quy mô", "2 tầng hầm, 25 tầng nổi"],
      ["Số căn hộ", "837 căn"],
      ["Loại căn", "1PN, 2PN, 3PN"],
      ["Thi công", "Quý I/2024 – dự kiến Quý I/2026"],
      ["Hình thức", "Sơ cấp & chuyển nhượng"],
    ],
    highlights: ["Sản phẩm mới, thiết kế tối ưu", "Liền kề FPT Plaza 1, 2 – tiện ích sẵn có", "Phù hợp ở và cho thuê", "Chính sách thanh toán linh hoạt"],
    units: [["1PN", "~45 – 50 m²"], ["2PN", "~56 – 75 m²"], ["3PN", "từ ~78 m²"]],
    cta: "Nhận bảng giá & mặt bằng FPT Plaza 3",
    faq: [
      ["FPT Plaza 3 khi nào nhận nhà?", "Theo thông tin dự án, FPT Plaza 3 thi công từ Quý I/2024 và dự kiến hoàn thành khoảng Quý I/2026. Liên hệ để nhận lịch bàn giao cập nhật."],
      ["FPT Plaza 3 có bao nhiêu căn?", "Dự án gồm 837 căn hộ trên 25 tầng nổi, 2 tầng hầm."],
    ],
  },
  {
    slug: "fpt-plaza-4",
    stats: [["1.395", "Căn hộ"], ["2.790 tỷ", "Tổng vốn đầu tư"], ["20", "Tầng nổi"], ["Q2/2027", "Dự kiến bàn giao"]],
    name: "FPT Plaza 4",
    status: "primary",
    statusLabel: "Đang mở bán",
    title: "FPT Plaza 4 Đà Nẵng – Bảng giá, mặt bằng căn hộ FPT Plaza 4",
    description: "Căn hộ FPT Plaza 4 Đà Nẵng: 1.395 căn, 20 tầng nổi, 3 hầm, vốn 2.790 tỷ, khởi công 3/2025, đủ điều kiện mở bán 11/2025. Nhận bảng giá FPT Plaza 4 qua Google Drive.",
    keywords: "FPT Plaza 4, căn hộ FPT Plaza 4, giá FPT Plaza 4, bảng giá FPT Plaza 4, mặt bằng FPT Plaza 4, FPT Plaza 4 Đà Nẵng",
    lead: "Dự án quy mô lớn nhất chuỗi FPT Plaza: 1.395 căn hộ, tổng vốn 2.790 tỷ đồng, đã đủ điều kiện bán nhà ở hình thành trong tương lai.",
    specs: [
      ["Tổng vốn đầu tư", "2.790 tỷ đồng"],
      ["Quy mô", "3 tầng hầm, 20 tầng nổi, tầng tum"],
      ["Số căn hộ", "1.395 căn"],
      ["Diện tích căn", "~45,3 – 263,4 m²"],
      ["Khởi công", "Tháng 3/2025"],
      ["Mở bán", "Đủ điều kiện từ 11/2025"],
      ["Bàn giao", "Dự kiến Quý II/2027"],
    ],
    highlights: ["Đủ điều kiện bán theo xác nhận của Sở Xây dựng", "Đa dạng diện tích từ 1PN đến căn lớn", "Thanh toán theo tiến độ", "Ngân hàng hỗ trợ vay"],
    units: [["1PN", "~45 – 50 m²"], ["2PN", "~56 – 75 m²"], ["3PN", "từ ~78 m²"], ["Căn lớn", "đến ~263 m²"]],
    cta: "Nhận bảng giá & mặt bằng FPT Plaza 4",
    faq: [
      ["FPT Plaza 4 bàn giao khi nào?", "Dự án khởi công tháng 3/2025, dự kiến bàn giao khoảng Quý II/2027."],
      ["FPT Plaza 4 đã được phép bán chưa?", "Tháng 11/2025, Sở Xây dựng Đà Nẵng xác nhận căn hộ FPT Plaza 4 đủ điều kiện bán nhà ở hình thành trong tương lai."],
    ],
  },
  {
    slug: "fpt-plaza-5",
    stats: [["~830", "Căn hộ (dự kiến)"], ["~25", "Tầng nổi (dự kiến)"], ["1–3PN", "Loại căn"], ["181+ ha", "Khu đô thị FPT City"]],
    name: "FPT Plaza 5",
    status: "upcoming",
    statusLabel: "Sắp mở bán · Nhận đăng ký",
    title: "FPT Plaza 5 Đà Nẵng – Bảng giá căn hộ FPT Plaza 5 mới nhất 2026",
    description: "Căn hộ FPT Plaza 5 tại khu đô thị FPT City Đà Nẵng: vị trí, quy mô dự kiến, mặt bằng, tiến độ và chính sách. Đăng ký nhận bảng giá FPT Plaza 5 sớm nhất qua Google Drive.",
    keywords: "FPT Plaza 5, căn hộ FPT Plaza 5, FPT Plaza 5 Đà Nẵng, giá bán FPT Plaza 5, bảng giá FPT Plaza 5, mặt bằng FPT Plaza 5",
    lead: "Giai đoạn tiếp theo của chuỗi FPT Plaza. Đăng ký sớm để nhận bảng giá đầu tiên và ưu tiên chọn căn đẹp khi dự án đủ điều kiện mở bán.",
    specs: [
      ["Quy mô", "Dự kiến ~25 tầng nổi, 2 tầng hầm*"],
      ["Số căn hộ", "Dự kiến ~830 căn*"],
      ["Loại căn", "1PN, 2PN, 3PN"],
      ["Tiến độ", "Đang triển khai – chờ thông báo mở bán"],
      ["Hình thức", "Sơ cấp từ chủ đầu tư"],
    ],
    note: "* Số liệu dự kiến theo thông tin thị trường, sẽ cập nhật theo công bố chính thức của chủ đầu tư.",
    highlights: ["Giá đợt đầu – dư địa tăng giá", "Ưu tiên chọn căn tầng đẹp, view biển", "Tiện ích FPT City đã hoàn thiện", "Nhận tài liệu & so sánh với FPT Plaza 4"],
    units: [["1PN", "~45 – 50 m²"], ["2PN", "~56 – 75 m²"], ["3PN", "từ ~78 m²"]],
    cta: "Đăng ký nhận bảng giá FPT Plaza 5",
    faq: [
      ["Giá bán căn hộ FPT Plaza 5 bao nhiêu?", "Chủ đầu tư chưa công bố bảng giá chính thức. Khách đăng ký nhận bảng giá tham khảo chuỗi FPT Plaza và được gửi giá FPT Plaza 5 ngay khi có thông tin."],
      ["Khi nào FPT Plaza 5 mở bán?", "Thời điểm mở bán phụ thuộc thông báo đủ điều kiện kinh doanh của Sở Xây dựng Đà Nẵng. Đăng ký để được cập nhật sớm nhất."],
      ["FPT Plaza 5 khác gì FPT Plaza 4?", "Cùng chủ đầu tư, cùng khu đô thị. FPT Plaza 4 đang mở bán; FPT Plaza 5 là giai đoạn kế tiếp. Bộ tài liệu có bảng so sánh chi tiết."],
    ],
  },
];

/* ---------------- ĐẤT NỀN ---------------- */
export const zones = [
  {
    slug: "phan-khu-v1",
    code: "V1",
    title: "Đất nền FPT City phân khu V1 – Lô biệt thự, lô góc giá tốt",
    description: "Đất nền FPT City Đà Nẵng phân khu V1: lô biệt thự, lô góc 2 mặt tiền, diện tích lớn. Nhận giỏ hàng đất V1 FPT City và bản đồ phân lô qua Google Drive.",
    keywords: "đất FPT City V1, phân khu V1 FPT City, đất nền V1 FPT Đà Nẵng, biệt thự FPT City",
    lead: "Phân khu có nhiều lô diện tích lớn, lô góc 2 mặt tiền phù hợp xây biệt thự, nhà vườn.",
    traits: ["Nhiều lô diện tích lớn (200 – 350+ m²)", "Lô góc 2 mặt tiền đường nội khu", "Phù hợp xây biệt thự, nhà ở gia đình", "Hạ tầng hoàn thiện"],
  },
  {
    slug: "phan-khu-v2",
    code: "V2",
    title: "Đất nền FPT City phân khu V2 – Gần Đại học FPT",
    description: "Đất nền FPT City phân khu V2 gần Đại học FPT Đà Nẵng, lô ~100 m², dễ xây trọ, nhà cho thuê. Nhận giỏ hàng đất V2 FPT City qua Google Drive.",
    keywords: "đất FPT City V2, phân khu V2 FPT City, đất nền V2 FPT Đà Nẵng, đất gần đại học FPT",
    lead: "Vị trí gần khuôn viên Đại học FPT, nhu cầu thuê nhà từ sinh viên, giảng viên cao quanh năm.",
    traits: ["Gần Đại học FPT & khu ký túc xá", "Lô phổ biến ~100 m²", "Phù hợp xây nhà cho thuê, căn hộ dịch vụ", "Thanh khoản tốt"],
  },
  {
    slug: "phan-khu-v3",
    code: "V3",
    title: "Đất nền FPT City phân khu V3 – Lô 100 m² khu dân cư hiện hữu",
    description: "Đất nền FPT City phân khu V3: lô ~100 m² trong khu dân cư đông đúc, gần trường học, tiện ích. Nhận giỏ hàng và bản đồ phân lô V3 qua Google Drive.",
    keywords: "đất FPT City V3, phân khu V3 FPT City, đất nền V3 FPT Đà Nẵng",
    lead: "Khu dân cư đã hình thành, nhiều nhà xây hoàn thiện – phù hợp ở thực và kinh doanh nhỏ.",
    traits: ["Dân cư hiện hữu đông", "Lô phổ biến ~100 m²", "Gần trường học & tiện ích nội khu", "Phù hợp ở thực, kinh doanh"],
  },
  {
    slug: "phan-khu-v4",
    code: "V4",
    title: "Đất nền FPT City phân khu V4 – Giỏ hàng cập nhật",
    description: "Đất nền FPT City phân khu V4 Đà Nẵng: vị trí, đặc điểm lô, quy hoạch. Nhận giỏ hàng đất V4 FPT City và bản đồ phân lô qua Google Drive.",
    keywords: "đất FPT City V4, phân khu V4 FPT City, đất nền V4 FPT Đà Nẵng",
    lead: "Phân khu nằm trong tổng thể quy hoạch đồng bộ của FPT City; giỏ hàng cập nhật theo tuần.",
    traits: ["Quy hoạch đồng bộ, đường nội khu rộng", "Nhiều lựa chọn diện tích", "Pháp lý sổ đỏ từng lô", "Giỏ hàng cập nhật hằng tuần"],
  },
  {
    slug: "phan-khu-v5",
    code: "V5",
    title: "Đất nền FPT City phân khu V5 – Lô 90–105 m² giá tốt",
    description: "Tổng hợp lô đất nền FPT City phân khu V5: diện tích 90–105 m², phù hợp ở và đầu tư. Nhận giỏ hàng đất V5 FPT City cập nhật qua Google Drive.",
    keywords: "đất FPT City V5, phân khu V5 FPT City, đất nền V5 FPT Đà Nẵng, giá đất V5 FPT",
    lead: "Phân khu được giao dịch sôi động với lô diện tích vừa phải, tổng tiền dễ tiếp cận.",
    traits: ["Lô phổ biến 90 – 105 m²", "Tổng tiền dễ tiếp cận", "Giao dịch sôi động, thanh khoản cao", "Phù hợp xây nhà ở & cho thuê"],
  },
  {
    slug: "phan-khu-v6",
    code: "V6",
    title: "Đất nền FPT City phân khu V6 – Gần FPT Complex, đường Nam Kỳ Khởi Nghĩa",
    description: "Đất nền FPT City phân khu V6 gần FPT Complex, sát trục Nam Kỳ Khởi Nghĩa và kênh sinh thái. Nhận giỏ hàng đất V6 FPT City qua Google Drive.",
    keywords: "đất FPT City V6, phân khu V6 FPT City, đất nền V6 FPT Đà Nẵng, đất gần FPT Complex",
    lead: "Vị trí gần tổ hợp văn phòng FPT Complex và trục đường Nam Kỳ Khởi Nghĩa – nguồn khách thuê là kỹ sư công nghệ.",
    traits: ["Gần FPT Complex – hàng nghìn kỹ sư", "Sát trục Nam Kỳ Khởi Nghĩa", "Có lô view kênh sinh thái", "Tiềm năng kinh doanh, cho thuê"],
  },
];
