# -*- coding: utf-8 -*-
UNIQ = {
'nhan-vien': dict(
  p90_h2='90 ngày đầu của <em>Nhân viên kinh doanh</em>',
  p90=[('Tuần 1–2', 'Học nghề', 'Đào tạo sản phẩm, pháp lý cơ bản, kịch bản gọi điện. Đi thực tế dự án cùng quản lý.', 'Bạn nói trôi chảy về 1–2 dự án chủ lực.'),
       ('Tuần 3–4', 'Gọi khách thật', 'Nhận lead được phân bổ, gọi và chăm khách, có người kèm nghe cùng. Hẹn lịch xem dự án đầu tiên.', 'Bạn có danh sách khách quan tâm của riêng mình.'),
       ('Tháng 2', 'Dẫn khách, học chốt', 'Cùng đồng đội dẫn khách đi nhà mẫu, học xử lý từ chối và đàm phán.', 'Bạn tự tin dẫn một buổi xem dự án.'),
       ('Tháng 3', 'Giao dịch đầu & xét lương', 'Hướng tới giao dịch đầu tay. Cuối tháng 3 xét lương và cấp bậc theo kết quả.', 'Đủ điều kiện, bạn lên Chuyên viên.')],
  fit=['Thích nói chuyện, không ngại gọi cho người lạ', 'Chấp nhận học nhiều trong 1–2 tháng đầu', 'Muốn thu nhập tăng theo kết quả', 'Đúng giờ, giữ lời hẹn với khách'],
  nofit=['Chỉ muốn lương cố định, không muốn chỉ tiêu', 'Ngại gọi điện, ngại gặp khách', 'Muốn kết quả nhanh mà không muốn học', 'Không làm việc linh hoạt được, kể cả buổi khách hẹn xem dự án'],
  faq_more=[('Người mới được phân bổ lead như thế nào?', 'Marketing đầu tổng chạy quảng cáo và chia data mỗi ngày cho cả đội, người mới cũng được nhận. Bạn được hướng dẫn cách gọi và chăm từng khách.'),
            ('Bao lâu thì lên Chuyên viên?', 'Xét mỗi 03 tháng dựa trên kết quả. Người làm tốt có thể lên ngay ở kỳ xét đầu tiên.'),
            ('Tôi không biết chạy quảng cáo, có sao không?', 'Không sao. Với Marketing 3 lớp, bạn được đào tạo, có người hướng dẫn chạy, và chi phí được hỗ trợ 50–100%.')]),
'chuyen-vien': dict(
  p90_h2='90 ngày đầu của <em>Chuyên viên kinh doanh</em>',
  p90=[('Tuần 1', 'Nắm giỏ hàng', 'Đào tạo sản phẩm, chính sách, pháp lý các dự án đang phân phối.', 'Bạn tư vấn được ngay các dự án chủ lực.'),
       ('Tuần 2–4', 'Bật hai nguồn khách', 'Nhận lead đầu tổng, lên kế hoạch marketing cá nhân và đề xuất ngân sách hỗ trợ 50–100%.', 'Hai nguồn khách chạy song song.'),
       ('Tháng 2', 'Tăng tỷ lệ chốt', 'Tư vấn chuyên sâu: bảng tính dòng tiền, so sánh căn, phương án vay. Quản lý cùng chốt deal lớn.', 'Giao dịch đầu tiên tại đây, cộng thưởng marketing.'),
       ('Tháng 3', 'Xét cấp bậc', 'Đánh giá theo kết quả, xét lương và cấp bậc.', 'Hướng tới Pro Sales lương 7–10 triệu/tháng.')],
  fit=['Đã có kinh nghiệm Sale BĐS hoặc Sale ngành khác', 'Muốn nguồn khách đều thay vì tự xoay xở', 'Chủ động xây thương hiệu cá nhân trên mạng xã hội', 'Muốn lên Pro Sales có lương tháng'],
  nofit=['Muốn làm tự do, không theo quy trình đội', 'Không muốn phối hợp với đồng đội', 'Ngại học dự án và sản phẩm mới', 'Muốn thu nhập cao mà không đặt mục tiêu'],
  faq_more=[('Ngân sách marketing hỗ trợ giải ngân thế nào?', 'Bạn đề xuất kế hoạch, ngân sách hỗ trợ 50–100% được giải ngân ngay khi đề xuất được duyệt.'),
            ('Chuyên viên khác Nhân viên kinh doanh ở điểm nào?', 'Chuyên viên đã có nền tảng, tự chủ nguồn khách hơn, tư vấn chuyên sâu hơn và là bước ngay trước Pro Sales.'),
            ('Thưởng marketing đến 10 triệu tính thế nào?', 'Mỗi giao dịch thành công được thưởng marketing đến 10 triệu, cộng thêm hoa hồng và thưởng nóng. Mức cụ thể theo từng dự án.')]),
'pro-sales': dict(
  p90_h2='90 ngày đầu của <em>Pro Sales</em>',
  p90=[('Tuần 1', 'Trao đổi 1:1 & nắm giỏ hàng', 'Thống nhất tiêu chí Pro Sales, nắm chính sách các dự án trọng điểm.', 'Bạn biết rõ mình cần đạt gì để giữ quyền lợi.'),
       ('Tuần 2–4', 'Kích hoạt khách giá trị lớn', 'Nhận lead đầu tổng, kết nối tệp khách đầu tư của bạn với giỏ hàng mới.', 'Lịch hẹn với khách đầu tư kín tuần.'),
       ('Tháng 2', 'Chốt deal lớn', 'Dẫn khách VIP, đàm phán phương án thanh toán và chính sách chủ đầu tư.', 'Giao dịch đầu tại đây, cộng thưởng marketing đến 10 triệu.'),
       ('Tháng 3', 'Làm hình mẫu', 'Chia sẻ kịch bản, kèm 1–2 bạn mới. Xét cấp bậc theo kết quả.', 'Mở đường lên Trưởng nhóm.')],
  fit=['Đã có giao dịch BĐS thực tế hoặc thành tích Sale nổi bật', 'Tự tin với khách đầu tư, khách giá trị lớn', 'Muốn lương tháng ổn định bên cạnh hoa hồng', 'Sẵn sàng chia sẻ kinh nghiệm cho đội'],
  nofit=['Chưa từng chốt giao dịch nào (hãy xem vị trí Nhân viên hoặc Chuyên viên)', 'Không muốn cam kết theo tiêu chí kết quả', 'Chỉ muốn làm một mình, không gắn với đội', 'Ngại cập nhật sản phẩm và chính sách mới'],
  faq_more=[('Lương 7–10 triệu có gồm hoa hồng không?', 'Không. Lương 7–10 triệu/tháng là mức sàn. Hoa hồng, thưởng marketing đến 10tr/giao dịch và thưởng nóng được tính thêm.'),
            ('Pro Sales có phải tự chạy quảng cáo không?', 'Không bắt buộc. Marketing đầu tổng phân lead cho đội. Nếu muốn chạy thêm, ngân sách được hỗ trợ 50–100%.'),
            ('Từ Pro Sales lên quản lý thế nào?', 'Pro Sales làm tốt và muốn dẫn đội có thể lên Trưởng nhóm, rồi Trưởng phòng lương 10–20 triệu/tháng.')]),
'truong-nhom': dict(
  p90_h2='90 ngày đầu của <em>người dẫn đội</em>',
  p90=[('Tháng 1', 'Nhận đội & nắm hệ thống', 'Nắm sản phẩm, quy trình phân lead, chỉ số của đội. Gặp 1:1 từng thành viên.', 'Bạn biết rõ điểm mạnh, điểm yếu của từng người.'),
       ('Tháng 1–2', 'Thiết lập nhịp đội', 'Họp đầu ngày, mục tiêu tuần, kèm 1:1. Phối hợp marketing đề xuất ngân sách cho đội.', 'Đội có nhịp làm việc đều và có khách mỗi ngày.'),
       ('Tháng 2–3', 'Tuyển & nhân bản', 'Tuyển thêm người, đào tạo người mới, cùng đội chốt các deal lớn.', 'Đội lớn hơn, giao dịch đều hơn.'),
       ('Tháng 3', 'Đánh giá cấp bậc', 'Kết quả của đội là thước đo thăng tiến.', 'Hướng tới Trưởng phòng lương 10–20 triệu/tháng.')],
  fit=['Đã dẫn nhóm Sale, hoặc là Sale giỏi muốn dẫn đội', 'Thích dạy người, kiên nhẫn kèm người mới', 'Quen làm việc với số liệu và mục tiêu', 'Muốn thu nhập gắn với kết quả của cả đội'],
  nofit=['Chỉ muốn bán một mình, không muốn quản người', 'Không có thời gian kèm cặp, đào tạo', 'Ngại tuyển dụng và xây đội', 'Không chịu được áp lực chỉ tiêu của đội'],
  faq_more=[('Tôi có thể mang đội cũ sang cùng không?', 'Có thể trao đổi. Bạn nói rõ khi tư vấn 1:1 để thống nhất phương án phù hợp.'),
            ('Trưởng nhóm và Trưởng phòng khác nhau thế nào?', 'Trưởng nhóm dẫn một nhóm Sale và cùng ra trận. Trưởng phòng vận hành cả phòng, quản lý các Trưởng nhóm, lương 10–20 triệu/tháng.'),
            ('Quản lý được đánh giá dựa trên gì?', 'Dựa trên kết quả của cả đội, đánh giá mỗi 03 tháng.')]),
'moi-ra-truong': dict(
  p90_h2='90 ngày đầu sau khi <em>cầm bằng</em>',
  p90=[('Tuần 1–2', 'Từ sinh viên thành người đi làm', 'Đào tạo sản phẩm, tác phong, kịch bản. Đi dự án lần đầu.', 'Bạn hiểu mình bán gì và bán cho ai.'),
       ('Tuần 3–4', 'Cuộc gọi đầu tiên', 'Gọi lead có người kèm nghe cùng, ghi chép, sửa từng câu.', 'Bạn hết ngại cầm máy gọi khách.'),
       ('Tháng 2', 'Dẫn khách cùng anh chị', 'Đi theo dẫn khách, học cách tư vấn và chốt.', 'Bạn tự dẫn được một buổi xem dự án.'),
       ('Tháng 3', 'Kỳ xét đầu tiên', 'Hướng tới giao dịch đầu tay. Xét lương và cấp bậc theo kết quả.', 'Sau 90 ngày, bạn biết rõ mình có hợp nghề không.')],
  fit=['Ngành nào cũng được, quan trọng là muốn học', 'Thích gặp gỡ, nói chuyện', 'Muốn thu nhập không bị giới hạn bởi thâm niên', 'Chịu vất vả vài tháng đầu để lớn nhanh'],
  nofit=['Muốn ngồi văn phòng 8 tiếng, ít gặp người', 'Chỉ tìm việc tạm thời vài tuần', 'Dễ nản khi bị khách từ chối', 'Cần thu nhập cố định cao ngay từ tháng đầu'],
  faq_more=[('Chưa từng đi làm, phỏng vấn thế nào?', 'Hoàng Hiệp gọi lại nói chuyện khoảng 15 phút về bạn và mong muốn của bạn. Không cần CV đẹp.'),
            ('Sau 90 ngày thấy không hợp thì sao?', 'Bạn vẫn mang theo kỹ năng giao tiếp, tư vấn và hiểu biết thị trường BĐS. Chúng tôi muốn bạn ở lại vì hợp, không phải vì bị giữ.'),
            ('Gia đình lo nghề Sale không ổn định?', 'Có hợp đồng lao động, BHYT, BHXH đầy đủ và 03 tháng xét lương. Thu nhập tăng theo kết quả, có lộ trình rõ ràng.')]),
}
OTHERS = {'nv': ('Nhân viên kinh doanh', 'Không cần kinh nghiệm, đào tạo từ đầu.'), 'cv': ('Chuyên viên kinh doanh', 'Đã có kinh nghiệm, cần nguồn khách đều.'),
          'pro': ('Pro Sales', 'Lương 7–10 triệu/tháng cho Sale đã có giao dịch.'), 'tn': ('Trưởng nhóm · Trưởng phòng', 'Trưởng phòng lương 10–20 triệu/tháng.'),
          'sv': ('Sale mới ra trường', 'Ngành nào cũng được, có người kèm.')}
